version: "3.2"
services:

  sql-server-db:
    container_name: sql-server
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SqlExpress!"
      ACCEPT_EULA: "Y"